inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml # add this line for Rails projects

AllCops:
  Exclude:
    - "bin/rails"
    - "bin/rake"
    - "bin/setup"
    - "bin/update"
    - "db/schema.rb"
    - "config/initializers/county_to_region_code.rb"

Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Exclude:
    - app/models/course.rb

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional


