inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml # add this line for Rails projects

AllCops:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: false
