language: ruby
cache: bundler
git:
  depth: false
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - bundle exec rake db:setup
before_install:
  - gem update --system
script:
  - bundle exec rake spec
  - bundle exec govuk-lint-ruby app config db lib spec --format clang
