version: '3.2'
volumes:
  dbdata:
services:
  db:
    image: postgres:9.6-alpine
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
     - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      cache_from:
        - ${dockerHubUsername:-dfedigital}/manage-courses-backend-poc:latest
    image: ${dockerHubUsername:-dfedigital}/manage-courses-backend-poc:latest
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - CC_TEST_REPORTER_ID=${CC_TEST_REPORTER_ID}
      - AGENT_JOBSTATUS=${AGENT_JOBSTATUS}
  bg-find-sync:
    build:
      args:
        - DOCKER_REPOSITORY=${dockerHubUsername:-dfedigital}
        - MANAGE_COURSES_BACKEND_IMAGE=${dockerHubImageName:-manage-courses-backend}
      context: bg-find-sync
      cache_from:
        - ${dockerHubUsername:-dfedigital}/manage-courses-bg-find-sync:latest
    image: ${dockerHubUsername:-dfedigital}/manage-courses-bg-find-sync:latest
    volumes:
      - .:/app
    depends_on:
      - web
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
