default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || '5432' %>

development:
  <<: *default
  database: manage_courses_backend_development

test:
  <<: *default
  database: manage_courses_backend_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
