---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Apply API
  contact:
    name: DfE
    email: becomingateacher@digital.education.gov.uk
  description: API for DfE's postgraduate teacher training course service
servers:
  - description: Production
    url: https://api2.publish-teacher-training-courses.service.gov.uk/api/public/v1
paths:
  /courses:
    get:
      operationId: public_api_v1_courses
      parameters:
        - name: filter
          in: query
          schema:
            type: object
          style: deepObject
        - name: sort
          in: query
          schema:
            type: object
          style: deepObject
      responses:
        '200':
          description: The list of courses in the current recruitment cycle
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseSingleResponse"
components:
  schemas:
    CourseSingleResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/CourseData"
        # included:
        jsonapi:
          $ref: "#/components/schemas/JSONAPI"
    Course:
      type: object
      required:
        - code
      properties:
        code:
          type: string
    CourseData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: integer
        type:
          type: string
        attributes:
          $ref: "#/components/schemas/Course"
        relationships:
          $ref: "#/components/schemas/CourseRelationships"
    CourseRelationships:
      type: object
      properties:
        accredited_body:
          $ref: "#/components/schemas/Relationship"
        provider:
          $ref: "#/components/schemas/Relationship"
        subjects:
          $ref: "#/components/schemas/RelationshipList"
    JSONAPI:
      type: object
      required:
        - version
      properties:
        version:
          type: string
    Relationship:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/RelationshipData"
        meta:
          type: object
    RelationshipData:
      type: object
      required:
        - type
        - id
      properties:
        type:
          type: string
        id:
          type: string
    RelationshipList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/RelationshipData"
