authentication:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
manage_api:
  # URL of the C# API app (manage-courses-api)
  base_url: http://localhost:6001
  # Auth token used between backend and manage-courses-api to authorize requests.
  secret: banana
search_api:
  # URL of the C# API app (search-and-compare-api)
  base_url: http://localhost:5001
  # Auth token used between backend and search-and-compare-api to authorize requests.
  secret: banana
current_recruitment_cycle_year: 2020
govuk_notify:
  api_key: please_change_me
  welcome_email_template_id: please_change_me
  course_update_email_template_id: please_change_me
publish_url: http://localhost:3000
find_url: http://localhost:3002
mcbg:
  redis_password: <%= SecureRandom.base64 %>
system_authentication_token: <%= SecureRandom.base64 %>
application: teacher-training-api
logstash:
  type: tcp
  host: # Our hostname here
  port: # Our port here
  ssl_enable: true
log_level: info
