authentication:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
current_recruitment_cycle_year: 2020
allocation_cycle_year: 2020
govuk_notify:
  api_key: please_change_me
  welcome_email_template_id: please_change_me
  course_update_email_template_id: please_change_me
  course_publish_email_template_id: please_change_me
  magic_link_email_template_id: please_change_me
  course_withdraw_email_template_id: please_change_me
  course_vacancies_filled_email_template_id: please_change_me
  course_sites_update_email_template_id: d5c8da46-9aa6-4c0a-8fad-ee782e89dbd3
  course_subjects_updated_email_template_id: b65aef1a-5847-44e6-90e0-88e0ea7898ec
  course_vacancies_updated_email_template_id: 3ae884e9-8495-44cf-9928-907b89a9f356
publish_url: http://localhost:3000
find_url: http://localhost:3002
mcbg:
  redis_password: <%= SecureRandom.base64 %>
system_authentication_token: <%= SecureRandom.base64 %>
application: teacher-training-api
logstash:
  type: tcp
  host: # Our hostname here
  port: # Our port here
  ssl_enable: true
log_level: info
magic_link:
  max_token_age: <%= 1.hour %>
commit_sha_file: COMMIT_SHA
skylight:
  enable: false
  authentication: please_change_me
