authentication:
  secret: secret
mcbg:
  redis_password:
system_authentication_token: "Ge32"
log_level: debug
gcp_api_key: please_change_me
throttled: 
  enabled: true
  global: 
    limit: 1
    period: 1
