search_api:
  base_url: https://api.pen.find-postgraduate-teacher-training.service.gov.uk
  secret: please_change_me
bg_jobs:
  find_bulk_sync:
    cron: "0 */6 * * *"
    class: "BulkSyncCoursesToFindJob"
    queue: find_sync
gcp_api_key: please_change_me
