manage_api:
  base_url: https://api.qa.publish-teacher-training-courses.service.gov.uk
  secret: please_change_me
search_api:
  base_url: https://api.qa.find-poqaraduate-teacher-training.service.gov.uk
  secret: please_change_me
