manage_api:
  base_url: https://bat-staging-manage-courses-api-app.azurewebsites.net
  secret: please_change_me
search_api:
  base_url: https://bat-staging-search-and-compare-api-app.azurewebsites.net
  secret: please_change_me
