govuk_notify:
  api_key: cafe-cafecafe-cafe-cafe-cafe-cafecafecafe-cafecafe-cafe-cafe-cafe-cafecafecafe
  welcome_email_template_id: please_change_me
  course_update_email_template_id: please_change_me
system_authentication_token: "Ge32"
gcp_api_key: please_change_me
publish_url: https://www.publish-teacher-training-courses.service.gov.uk
find_url: https://www2.find-postgraduate-teacher-training.education.gov.uk
